---
title: "人口データ作成の自動化"
author: "nekota"
date: "2024-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## データ収集先

毎月推計人口データは大阪府のページでエクセルファイルとして公開されています。

新しいものと古いものでデータの形式が異なります。
また、配布しているページも異なるので整理が必要です。

||データ|期間|
|---|---|---|
|新しい|全てあり|令和３年（２０２１年）１１月以降|
|古い|増減の一部なし|令和２年（２０２０年）１１月から令和３年（２０２１年）９月まで|
|国勢調査月|全てあり？|令和２年（２０２０年）１０月|
|最も古い|人口、世帯のみ|平成２７年（２０１５年）１１月から令和２年（２０２０年）９月まで|


データの得られるウェブページは随時（国勢調査が行われる毎）に変更されることが
予想されます。

データを配布する形式は今はエクセルの「xlsx」形式ですが、凄く古いものはxls形式のものもあります。

||site|
|---|---|
|新しい|https://www.pref.osaka.lg.jp/toukei/jinkou/jinkou-xlslist.html|
|古い|https://www.pref.osaka.lg.jp/toukei/jinkou/jinkou-xlslist.html|
|国勢調査年|https://www.pref.osaka.lg.jp/toukei/top_portal/kokucho.html|
|最も古い|https://www.pref.osaka.lg.jp/toukei/jinkou/jinkou-h.html|

データ収集を地価公示の資料で利用するだけならば過去５年まで
現在時点で言えば2018年（平成３０年）分までがあれば十分です。
上記のデータ区分で言う「最も古い」ところでデータの取りやすい平成２７年（２０１５年）１１月以降を
収集することにします。

一方、年齢別人口データは、別のファイルで配布されています。

||データ|期間|
|---|---|---|
|新しい|毎月のデータあり|令和２年（２０２０年）１０月以降|
|古い|１０月のデータのみ|平成２９年（２０１７年）１０月から令和２年（２０２０年）１０月まで|


||site|
|---|---|
|新しい|https://www.pref.osaka.lg.jp/toukei/jinkou/jinkou-xlslist.html|
|最も古い|https://www.pref.osaka.lg.jp/toukei/jinkou/jinkou-h.html|


## 配布されているデータの形式とどのように整理するか

エクセルファイルにどのようにデータが配置されているかを確認して、
そのパターンを把握します。

これら異なるデータの並びを、ある統一した並びにそろえる方法を考えます。


### 推計人口データ

#### 新しいデータ

１ファイルに１月のデータ

|仮の列名|データ内容|最終の列名|
|---|---|---|
|X1| 市区町村名 |areaname
|X2| 世帯数   |  hh
|X3| 人口総数  | pt
|X4| 男     |    pm
|X5| 女     |    pf
|X6|  １年の増減総数  |yct
|X7|  １年の自然増減  |ycn
|X8|  １年の出生    | yib
|X9|  １年の死亡    | ydd
|X10| １年の社会増減  |ycs
|X11|  １月の増減総数 |lmct
|X12|  １月の自然増減 |lmcn
|X13|  １月の出生   |  lmib
|X14|  １月の死亡   |   lmdd
|X15|  １月の社会増減 | lmcs
|X16| １世帯当たり人員 |pph
|X17| 人口密度     |    ppa

このデータの形式を人口データの統一形式にする

#### 古いデータ

１ファイルに１月のデータだが、１年間の増減データがない

|仮の列名|データ内容|最終の列名|
|---|---|---|
|X1| 市区町村名 |areaname
|X2| 世帯数   |  hh
|X3| 人口総数  | pt
|X4| 男     |    pm
|X5| 女     |    pf
|X6|  １月の増減総数 |lmct
|X7|  １月の自然増減 |lmcn
|X8|  １月の出生   |  lmib
|X9|  １月の死亡   |   lmdd
|X10|  １月の社会増減 | lmcs
|X11| １世帯当たり人員 |pph
|X12| 人口密度     |    ppa

#### 国勢調査月データ

１ファイルに国勢調査の沢山のデータのシートが存在します。
そして、シート名「表9-1」のシートに人口データがあります。

人口の増減データ（１年、１月）はありません。

世帯数は総数と一般世帯数があり、総数側が他の年の世帯数に一致します。
１世帯当たり人数は計算が必要です。

#### 最も古いデータ

スクレイピングしたエクセルファイルは、2010年11月からのファイルがあります。
しかし、2010年11月から2015年10月までは、地域のグループ名称が一部異なっています。

また、ファイル内のデータの形式は、１ファイルに複数シートがあり、
１シートに１月分のデータが配置されています。
更に、１シートでのデータ配置が整然データとなっておらず、
１行に２地域のデータが配置されています。

データの内容は人口のみで、増減はありません。


### 年齢別人口データ

全て同じデータ形式

整然データになっておらず、

行について、男女合わせて、男のみ、女のみの３区分データがある。

列については以下の通り


|仮の列名|データ内容|最終の列名|
|---|---|---|
|X1| 市区町村名 |areaname|
|X2| 総数   | t |
|X3|0から4歳|t1|
|X4|5から9歳|t2|
|X5|10から14歳|t3|
|X6|15から19歳|t4|
|X7|20から24歳|t5|
|X9|25から29歳|t6|
|X10|30から34歳|t7|
|X11|35から39歳|t8|
|X12|40から44歳|t9|
|X13|45から49歳|t10|
|X14|50から54歳|t11|
|X15|55から59歳|t12|
|X16|60から64歳|t13|
|X17|65から69歳|t14|
|X18|70から74歳|t15|
|X19|75から79歳|t16|
|X20|80から84歳|t17|
|X21|85から89歳|t18|
|X22|90から94歳|t19|
|X23|95歳以上|t20|

整然データにするために、同一地域を１行にまとめ、男女総数、男のみ、女のみを１行にする。





